meta:
  engine: 4.0.2
  name: magellan
  version: 0.1
  author: TildeWill
  url: https://github.com/TildeWill/magellan
  tags: ["wired", "monoblock", "low-profile", "trackpad"]
  notes:
    pcb_thickness: "1.2 for a strong hot swap connection"

units:
  kx: cx
  ky: cy

  mcu_width: 20.5
  mcu_height: 33

  trackpad_width: 67
  trackpad_height: 49

points:
  key:
    padding: 1ky
    spread: 1kx
    width: 1kx
    height: 1ky
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      key.tags: key
      columns:
        outer:
          key:
            column_net: C0
            mirror.column_net: C0
        pinky:
          key:
            column_net: C1
            mirror.column_net: C1
        ring:
          key:
            column_net: C2
            mirror.column_net: C2
        middle:
          key:
            column_net: C3
            mirror.column_net: C3
        index:
          key:
            column_net: C4
            mirror.column_net: C4
        inner:
          key:
            column_net: C5
            mirror.column_net: C5

      rows:
        thumb:
          row_net: R4
          mirror.row_net: R9
        bottom:
          row_net: R3
          mirror.row_net: R8
        home:
          row_net: R2
          mirror.row_net: R7
        top:
          row_net: R1
          mirror.row_net: R6
        num:
          row_net: R0
          mirror.row_net: R5
      rotate: -15
      mirror: &mirror
        ref: matrix_inner_home
        distance: trackpad_width + 1.5kx


    keeb_center:
      anchor:
        ref.aggregate.parts: [matrix_inner_num, mirror_matrix_inner_num, matrix_inner_thumb, mirror_matrix_inner_thumb]

    #  Controller
    mcu_center:
      anchor:
        ref.aggregate.parts: [ matrix_inner_num, mirror_matrix_inner_num ]
        shift: [0, -9]
      key:
        width: mcu_width
        height: mcu_height

    #  Azoteq TPS65 Trackpad
    trackpad_center:
      anchor:
        ref: keeb_center
        shift: [0, -20]
      key:
        width: trackpad_width
        height: trackpad_height

outlines:
  keys:
    - what: rectangle
      where: key
      size: [kx/2, ky/2]

  full_outline:
    - what: polygon
      operation: stack
      fillet: 4
      points:
        - ref: matrix_outer_num
          shift: [ -0.75kx, 0.75ky ]
        - ref: matrix_inner_num
          shift: [ 0.75kx, 0.75ky ]
        - ref: mirror_matrix_inner_num
          shift: [ 0.75kx, 0.75ky ]
        - ref: mirror_matrix_outer_num
          shift: [ -0.75kx, 0.75ky ]
        - ref: mirror_matrix_outer_thumb
          shift: [ -0.75kx, -0.75ky ]
        - ref: mirror_matrix_inner_thumb
          shift: [ 0.75kx, -0.75ky ]
        - ref: matrix_inner_thumb
          shift: [ 0.75kx, -0.75ky ]
        - ref: matrix_outer_thumb
          shift: [ -0.75kx, -0.75ky ]

  top_plate:
    - name: full_outline
    - operation: subtract
      name: keys

pcbs:
  board:
    outlines:
      combo:
        outline: full_outline
    footprints:
      choc:
        what: choc
        where:
          - /matrix_.*/
        params:
          show_keycaps: true
          reverse: false
          hotswap: true
          solder: false
          from: "{{column_net}}"
          to: "{{colrow}}"

      hole1:
        what: mounting_hole
        where:
          ref: matrix_outer_num
          shift: [0.5kx, -0.5ky]
      hole2:
        what: mounting_hole
        where:
          ref: matrix_outer_thumb
          shift: [ 0.5kx, 0.5ky ]
      hole3:
        what: mounting_hole
        where:
          ref: matrix_index_num
          shift: [ 0.5kx, -0.5ky ]
      hole4:
        what: mounting_hole
        where:
          ref: matrix_index_thumb
          shift: [ 0.5kx, 0.5ky ]

      hole5:
        what: mounting_hole
        where:
          ref: mirror_matrix_outer_num
          shift: [ 0.5kx, -0.5ky ]
      hole6:
        what: mounting_hole
        where:
          ref: mirror_matrix_outer_thumb
          shift: [ 0.5kx, 0.5ky ]
      hole7:
        what: mounting_hole
        where:
          ref: mirror_matrix_index_num
          shift: [ 0.5kx, -0.5ky ]
      hole8:
        what: mounting_hole
        where:
          ref: mirror_matrix_index_thumb
          shift: [ 0.5kx, 0.5ky ]

      diode:
        what: diode
        where:
          - /matrix_.*/
        params:
          include_tht: false
          side: back
          from: "{{colrow}}"
          to: "{{row_net}}"
          designator: "D"
        adjust:
          shift: [-3.4, -6]
          rotate: 180


      mcu:
        what: elite-c
        params:
#          D3: 'R3'
#          D2: 'R2'
          GND0: 'GND0'
          #          GND1: ''
          D1: 'SDA'
          D0: 'SCL'
          D4: 'R0'
          C6: 'R1'
          D7: 'R2'
          E6: 'R3'
          B4: 'R4'
#          B5: ''

          B7: 'C0'
          D5: 'C1'
          C7: 'C2'
          F1: 'C3'
          F0: 'C4'

          B6: 'R5'
          B2: 'R6'
          B3: 'R7'
          B1: 'R8'
          F7: 'R9'
#          F6: 'C7'
#          F5: 'C8'
#          F4: 'C9'
          VCC: 'VCC'
          RST: 'RST'
          GND2: 'GND'
        #          B0: ''
        where:
          ref: mcu_center
          rotate: -90

      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: keeb_center
          shift: [ -20, 20 ]

      trackpad:
        what: azoteq_trackpad
        params:
          GND: 'GND0'
        where:
          ref: trackpad_center

      github:
        what: text_metal
        where:
          ref: keeb_center
          shift: [ 0, -30 ]
        params:
          text: "https://github/com/TildeWill/magellan"
          h_size: 2
