meta:
  engine: 4.0.2
  name: magellan
  version: 0.1
  author: TildeWill
  url: https://github.com/TildeWill/magellan
  tags: ["wired", "monoblock", "low-profile", "split", "trackpad"]

units:
  kx: cx
  ky: cy

  # MCU
  mcu_overhang_y: 2.54
  mcu_spacing_x: 2.72
  mcu_x: 17.78 + mcu_spacing_x
  mcu_y: 30.48 + mcu_overhang_y

points:
  key:
    padding: 1ky
    spread: 1kx
    width: 1kx
    height: 1ky
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      key.tags: key
      columns:
        pinky:
          key.column_net: C0
        ring:
          key.column_net: C1
        middle:
          key.column_net: C2
        index:
          key.column_net: C3
        inner:
          key.column_net: C4

      rows:
        bottom:
#          row_net: R0
        home:
#          row_net: R1
        top:
#          row_net: R2

    thumb_cluster:
      key:
        tags: key
      anchor:
        ref: matrix_middle_bottom
        shift: [0, -1ky]
      columns:
        one:
          key.column_net: C2
        two:
          key.column_net: C3
        three:
          key.column_net: C4
      rows:
        thumb_row:
#          row_net: R3

    keeb_center:
      anchor:
        ref: matrix_inner_top
        shift: [6kx, 0]

    #  Controller
    controller:
      anchor:
        ref: keeb_center
        shift: [0, -9]
      key:
        name: mcu
        width: mcu_x
        height: mcu_y

    #  Azoteq TPS65 Trackpad
    trackpad:
      anchor:
        ref: keeb_center
        shift: [0, -16]
      key:
        name: trackpad
        width: 65
        height: 49

outlines:
  _keys:
    - what: rectangle
      where: [[key, -enter, -space]]
      size: [kx/2, ky/2]

  wing_outline:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [ -0.75kx, 0.75ky ]
        - ref: matrix_inner_top
          shift: [ 2kx, 0.75ky ]
        - ref: thumb_cluster_three_thumb_row
          shift: [ 2kx, -0.75ky ]
        - ref: thumb_cluster_one_thumb_row
          shift: [ -0.75kx, -0.75ky ]
#        - ref: thumb_cluster_one_thumb_row
#          shift: [ -0.75kx, 0.25ky ]
        - ref: matrix_pinky_bottom
          shift: [ -0.75kx, -0.75ky ]


  middle_outline:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_inner_top
          shift: [ 0.75kx, 0.75ky ]
        - ref: matrix_inner_top
          shift: [ 6.75kx, 0.75ky ]
        - ref: thumb_cluster_three_thumb_row
          shift: [ 6.75kx, -0.75ky ]
        - ref: thumb_cluster_three_thumb_row
          shift: [ 0.75kx, -0.75ky ]

pcbs:
  wing_board:
    outlines:
      wing:
        outline: wing_outline
    footprints:
      choc:
        what: choc
        where:
          - /matrix_.*/
          - /thumb_cluster_.*/
        params:
          show_keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

#      diode:
#        what: diode
#        where:
#          - /matrix_.*/
#          - /thumb_cluster_.*/
#        params:
#          include_tht: false
#          side: back
#          from: "{{colrow}}"
#          to: "{{row_net}}"
#          designator: "D"
#        adjust:
#          shift: [-1.4, -6]
#          rotate: 180

      front_ffc_connector:
        what: ffc_connector
        where:
          ref: matrix_inner_home
          shift: [20, -36]
          rotate: 90
        params:
          side: "B"
          P0: "C0"
          P1: "C1"
          P2: "C2"
          P3: "C3"
          P4: "C4"

#      back_ffc_connector:
#        what: ffc_connector
#        where:
#          ref: matrix_inner_home
#          shift: [1kx, 0]
#          rotate: 90
#        params:
#          side: "B"
#          P1: "R0"
#          P2: "R1"
#          P3: "R2"

  middle_board:
    outlines:
      middle:
        outline: middle_outline
    footprints:
      # Controller Area
      promicro:
        what: promicro
        params:  # Pin Assignments (Controller on top facing down)
          orientation: "up"
          # Left side of MCU
          P0: "R0" # Left Row
          P1: "R1" # Left Row
          # GND
          # GND
          P2: "SDA" # I2C
          P3: "SCL" # I2C
          P4: "R2" # Left Row
          P5: "R3" # Left Row
          P6: "R4" # Right Row
          P7: "R5" # Right Row
          P8: "R6" # Right Row
          P9: "R7" # Right Row

          # Right side of MCU
          # RAW
          # GND       # Ground
          # RST       # Reset pin
          # VCC       # External Power
          P21: "C0" # Column
          P20: "C1" # Column
          P19: "C2" # Column
          P18: "C3" # Column
          P15: "C4" # Column
          # P14:
          # P16:
          # P10:
        where:
          ref: mcu
          rotate: -90

      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: keeb_center
          shift: [0, -40]

      trackpad:
        what: azoteq_trackpad
        params:
        where:
          ref: trackpad

      github:
        what: text_metal
        where:
          ref: keeb_center
          shift: [0, -40]
        params:
          text: "github/com/TildeWill/magellan"
          h_size: 2
