meta:
  engine: 4.0.2
  name: magellan
  version: 0.1
  author: TildeWill
  url: https://github.com/TildeWill/magellan
  tags: ["wired", "monoblock", "low-profile", "split", "trackpad"]
  notes:
    pcb_thickness: "1.2 for a strong hot swap connection"

units:
  kx: cx
  ky: cy

  # MCU
  mcu_overhang_y: 2.54
  mcu_spacing_x: 2.72
  mcu_x: 17.78 + mcu_spacing_x
  mcu_y: 30.48 + mcu_overhang_y

  trackpad_width: 67
  middle_outline_width: trackpad_width
  tab_height: 6

  mirror_width: middle_outline_width + 40

points:
  key:
    padding: 1ky
    spread: 1kx
    width: 1kx
    height: 1ky
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      key.tags: key
      columns:
        pinky:
          key:
            column_net: C0
            mirror.column_net: C0
          rows.thumb.skip: true
        ring:
          key:
            column_net: C1
            mirror.column_net: C1
          rows.thumb.skip: true
        middle:
          key:
            column_net: C2
            mirror.column_net: C2
        index:
          key:
            column_net: C3
            mirror.column_net: C03
        inner:
          key:
            column_net: C4
            mirror.column_net: C4

      rows:
        thumb:
          row_net: R3
          mirror.row_net: R3
        bottom:
          row_net: R2
          mirror.row_net: R2
        home:
          row_net: R1
          mirror.row_net: R1
        top:
          row_net: R0
          mirror.row_net: R0

      mirror: &mirror
        ref: matrix_inner_top
        distance: mirror_width

    ffc_centers:
      anchor:
        ref: matrix_inner_thumb
        shift: [12, 1]
      columns:
        wing:
        middle:
          key:
            spread: 12
      rows:
        ffcs:
      mirror: &mirror
        ref: matrix_inner_top
        distance: mirror_width

    keeb_center:
      anchor:
        ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top, matrix_inner_thumb, mirror_matrix_inner_thumb]

    #  Controller
    mcu_center:
      anchor:
        ref: keeb_center
        shift: [16, 16]
      key:
        width: mcu_x
        height: mcu_y

    #  Azoteq TPS65 Trackpad
    trackpad_center:
      anchor:
        ref: keeb_center
        shift: [0, 9]

outlines:
  _keys:
    - what: rectangle
      where: [[key, -enter, -space]]
      size: [kx/2, ky/2]

  tab_top:
    - what: rectangle
      where:
        ref: keeb_center
        shift: [0, 10]
      size: [2middle_outline_width, tab_height]

  tab_bottom:
    - what: rectangle
      where:
        ref: keeb_center
        shift: [0, -10]
      size: [2middle_outline_width, tab_height]

  wing_outline:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [ -0.5kx, 0.5ky ]
        - ref: matrix_inner_top
          shift: [ 0.5kx + 8, 0.5ky ]
        - ref: matrix_inner_thumb
          shift: [ 0.5kx + 8, -0.5ky ]
        - ref: matrix_middle_thumb
          shift: [ -0.5kx, -0.5ky ]
        - ref: matrix_middle_thumb
          shift: [ -0.5kx, 0.5ky ]
        - ref: matrix_pinky_bottom
          shift: [ -0.5kx, -0.5ky ]

  mirror_wing_outline:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_pinky_top
          shift: [ -0.5kx, 0.5ky ]
        - ref: mirror_matrix_inner_top
          shift: [ 0.5kx + 8, 0.5ky ]
        - ref: mirror_matrix_inner_thumb
          shift: [ 0.5kx + 8, -0.5ky ]
        - ref: mirror_matrix_middle_thumb
          shift: [ -0.5kx, -0.5ky ]
        - ref: mirror_matrix_middle_thumb
          shift: [ -0.5kx, 0.5ky ]
        - ref: mirror_matrix_pinky_bottom
          shift: [ -0.5kx, -0.5ky ]

  middle_outline:
    - what: rectangle
      where: keeb_center
      fillet: 2
      size: [middle_outline_width, 4ky]

  combo:
    - name: wing_outline
    - operation: add
      name: mirror_wing_outline
    - operation: add
      name: middle_outline
    - operation: add
      name: tab_top
    - operation: add
      name: tab_bottom

pcbs:
  left_board:
    outlines:
      wing:
        outline: wing_outline
    footprints:
      choc:
        what: choc
        where:
          - /^matrix_.*/
        params:
          show_keycaps: true
          reverse: false
          hotswap: true
          solder: false
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode:
        what: diode
        where:
          - /^matrix_.*/
        params:
          include_tht: false
          side: back
          from: "{{colrow}}"
          to: "{{row_net}}"
          designator: "D"
        adjust:
          shift: [-3.4, -6]
          rotate: 180

      wing_ffc_connector:
        what: ffc_connector
        where:
          ref: ffc_centers_wing_ffcs
          rotate: 90
        params:
          side: "F"
          P9: "R3"
          P8: "R2"
          P7: "R1"
          P6: "R0"
          P5: "C0"
          P4: "C1"
          P3: "C2"
          P2: "C3"
          P1: "C4"
#          P0: ""

  right_board:
    outlines:
      wing:
        outline: mirror_wing_outline
    footprints:
      choc:
        what: choc
        where:
          - /^mirror_matrix_.*/
        params:
          show_keycaps: true
          reverse: false
          hotswap: true
          solder: false
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode:
        what: diode
        where:
          - /^mirror_matrix_.*/
        params:
          include_tht: false
          side: back
          from: "{{colrow}}"
          to: "{{row_net}}"
          designator: "D"
        adjust:
          shift: [ -3.4, -6 ]
          rotate: 180

      wing_ffc_connector_mirror:
        what: ffc_connector
        where:
          ref: mirror_ffc_centers_wing_ffcs
          rotate: 90
        params:
          side: "F"
          P0: "C0"
          P1: "C1"
          P2: "C2"
          P3: "C3"
          P4: "C4"
          P5: "R7"
          P6: "R6"
          P7: "R5"
          P8: "R4"
          P9: ""

  middle_board:
    outlines:
      wing:
        outline: middle_outline
    footprints:

      middle_ffc_connector:
        what: ffc_connector
        where:
          ref: ffc_centers_middle_ffcs
          rotate: -90
        params:
          side: "F"
          P0: "R3"
          P1: "R2"
          P2: "R1"
          P3: "R0"
          P4: "C0"
          P5: "C1"
          P6: "C2"
          P7: "C3"
          P8: "C4"
#          P9: ""

      middle_ffc_connector_mirror:
        what: ffc_connector
        where:
          ref: mirror_ffc_centers_middle_ffcs
          rotate: -90
        params:
          side: "F"
          P9: "C0"
          P8: "C1"
          P7: "C2"
          P6: "C3"
          P5: "C4"
          P4: "R7"
          P3: "R6"
          P2: "R5"
          P1: "R4"
#          P0: ""

      # Controller Area
      mcu:
        what: elite-c
        params:
          D3: 'SCL'
          D2: 'SDA'
          GND0: 'GND0'
#          GND1: ''
          D1: 'R3'
          D0: 'R2'
          D4: 'R1'
          C6: 'R0'
#          D7: ''
#          E6: ''
#          B4: ''
#          B5: ''

          B7: 'C0'
          D5: 'C1'
          C7: 'C2'
          F1: 'C3'
          F0: 'C4'

#          B6: ''
#          B2: ''
#          B3: ''
#          B1: ''
          F7: 'R4'
          F6: 'R5'
          F5: 'R6'
          F4: 'R7'
          VCC: 'VCC'
          RST: 'RST'
          GND2: 'GND'
#          B0: ''
        where:
          ref: mcu_center
          rotate: -90

      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: keeb_center
          shift: [ 0, -22 ]

      trackpad:
        what: azoteq_trackpad
        params:
          GND: 'GND0'
        where:
          ref: trackpad_center

      github:
        what: text_metal
        where:
          ref: keeb_center
          shift: [ 0, -30 ]
        params:
          text: "https://github/com/TildeWill/magellan"
          h_size: 2
