meta:
  engine: 4.0.2
  name: magellan
  version: 0.1
  author: TildeWill
  url: https://github.com/TildeWill/magellan
  tags: ["wired", "monoblock", "low-profile", "split", "trackpad"]
  notes:
    pcb_thickness: "1.2 for a strong hot swap connection"

units:
  kx: cx
  ky: cy

  # MCU
  mcu_overhang_y: 2.54
  mcu_spacing_x: 2.72
  mcu_x: 17.78 + mcu_spacing_x
  mcu_y: 30.48 + mcu_overhang_y

points:
  key:
    padding: 1ky
    spread: 1kx
    width: 1kx
    height: 1ky
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      key.tags: key
      columns:
        pinky:
          key.column_net: FFC_C0
          rows.thumb.skip: true
        ring:
          key.column_net: FFC_C1
          rows.thumb.skip: true
        middle:
          key.column_net: FFC_C2
        index:
          key.column_net: FFC_C3
        inner:
          key.column_net: FFC_C4

      rows:
        thumb:
          row_net: FFC_R3
        bottom:
          row_net: FFC_R2
        home:
          row_net: FFC_R1
        top:
          row_net: FFC_R0

      mirror: &mirror
        ref: matrix_inner_top
        distance: 5kx

    ffc_center:
      anchor:
        ref: matrix_inner_thumb
        shift: [12, 1]

    vias:
      key:
        tags: via
        padding: 1
        spread: 1
      anchor:
        ref: ffc_center
        shift: [-4, -6]
      columns:
        one:
      rows:
        p0:
          row_net: FFC_R3
        p1:
          row_net: FFC_R2
        p2:
          row_net: FFC_R1
        p3:
          row_net: FFC_R0

    keeb_center:
      anchor:
        ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top, matrix_inner_thumb, mirror_matrix_inner_thumb]

    #  Controller
    controller:
      anchor:
        ref: keeb_center
        shift: [0, -9]
      key:
        name: mcu_center
        width: mcu_x
        height: mcu_y

    #  Azoteq TPS65 Trackpad
    trackpad:
      anchor:
        ref: keeb_center
        shift: [0, -16]
      key:
        name: trackpad_center
        width: 65
        height: 49

outlines:
  _keys:
    - what: rectangle
      where: [[key, -enter, -space]]
      size: [kx/2, ky/2]

  left_wing_outline:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [ -0.5kx, 0.5ky ]
        - ref: matrix_inner_top
          shift: [ 0.5kx + 8, 0.5ky ]
        - ref: matrix_inner_thumb
          shift: [ 0.5kx + 8, -0.5ky ]
        - ref: matrix_middle_thumb
          shift: [ -0.5kx, -0.5ky ]
        - ref: matrix_middle_thumb
          shift: [ -0.5kx, 0.5ky ]
        - ref: matrix_pinky_bottom
          shift: [ -0.5kx, -0.5ky ]
  right_wing_outline:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_pinky_top
          shift: [ -0.5kx, 0.5ky ]
        - ref: mirror_matrix_inner_top
          shift: [ 0.5kx + 8, 0.5ky ]
        - ref: mirror_matrix_inner_thumb
          shift: [ 0.5kx + 8, -0.5ky ]
        - ref: mirror_matrix_middle_thumb
          shift: [ -0.5kx, -0.5ky ]
        - ref: mirror_matrix_middle_thumb
          shift: [ -0.5kx, 0.5ky ]
        - ref: mirror_matrix_pinky_bottom
          shift: [ -0.5kx, -0.5ky ]

  middle_outline:
    - what: rectangle
      where: keeb_center
      fillet: 2
      size: [4kx, 4ky]

  combo:
    - name: left_wing_outline
    - operation: add
      name: right_wing_outline
    - operation: add
      name: middle_outline
pcbs:
  combo_board:
    outlines:
      wing:
        outline: combo
    footprints:
      choc:
        what: choc
        where:
          - /matrix_.*/
          - /thumb_cluster_.*/
        params:
          show_keycaps: true
          reverse: false
          hotswap: true
          solder: false
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode:
        what: diode
        where:
          - /matrix_.*/
        params:
          include_tht: false
          side: back
          from: "{{colrow}}"
          to: "{{row_net}}"
          designator: "D"
        adjust:
          shift: [-3.4, -6]
          rotate: 180

      ffc_connector_left:
        what: ffc_connector
        where:
          ref: ffc_center
          rotate: 90
        params:
          side: "F"
          P0: "FFC_R3"
          P1: "FFC_R2"
          P2: "FFC_R1"
          P3: "FFC_R0"
          P4: "FFC_C0"
          P5: "FFC_C1"
          P6: "FFC_C2"
          P7: "FFC_C3"
          P8: "FFC_C4"

      ffc_vias:
        what: via
        where:
          - /vias_.*/
        params:
          net: "{{row_net}}"


      # Controller Area
      promicro:
        what: promicro
        params:  # Pin Assignments (Controller on top facing down)
          orientation: "up"
          # Left side of MCU
          P0: "R0" # Left Row
          P1: "R1" # Left Row
          # GND
          # GND
          P2: "SDA" # I2C
          P3: "SCL" # I2C
          P4: "R2" # Left Row
          P5: "R3" # Left Row
          P6: "R4" # Right Row
          P7: "R5" # Right Row
          P8: "R6" # Right Row
          P9: "R7" # Right Row

          # Right side of MCU
          # RAW
          # GND       # Ground
          # RST       # Reset pin
          # VCC       # External Power
          P21: "C0" # Column
          P20: "C1" # Column
          P19: "C2" # Column
          P18: "C3" # Column
          P15: "C4" # Column
          # P14:
          # P16:
          # P10:
        where:
          ref: mcu_center
          rotate: -90

      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: keeb_center
          shift: [0, -40]

      trackpad:
        what: azoteq_trackpad
        params:
        where:
          ref: trackpad_center

      github:
        what: text_metal
        where:
          ref: keeb_center
          shift: [0, -40]
        params:
          text: "github/com/TildeWill/magellan"
          h_size: 2
