meta:
  engine: 4.0.2
  name: magellan
  version: 0.1
  author: TildeWill
  url: https://github.com/TildeWill/magellan
  tags: ["wired", "monoblock", "low-profile", "split", "trackpad"]

units:
  kx: cx
  ky: cy

  # MCU
  mcu_overhang_y: 2.54
  mcu_spacing_x: 2.72
  mcu_x: 17.78 + mcu_spacing_x
  mcu_y: 30.48 + mcu_overhang_y

points:
  key:
    padding: 1ky
    spread: 1kx
    width: 1kx
    height: 1ky
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      key.tags: key
      columns:
        pinky:
          key.column_net: C0
        ring:
          key.column_net: C1
        middle:
          key.column_net: C2
        index:
          key.column_net: C3
        inner:
          key.column_net: C4

      rows:
        bottom:
          row_net: R2
          mirror.row_net: R6
        home:
          row_net: R1
          mirror.row_net: R5
        top:
          row_net: R0
          mirror.row_net: R4
      mirror: &mirror
        ref: matrix_inner_top
        distance: 6kx

    thumb_cluster:
      key:
        tags: key
      anchor:
        ref: matrix_inner_bottom
        shift: [0, -1ky]
      columns:
        one:
          key.column_net: C2
        two:
          key.column_net: C3
        three:
          key.column_net: C4
      rows:
        thumb_row:
          row_net: R3
          mirror.row_net: R7

      mirror: &thumb_mirror
        ref: matrix_inner_top
        distance: 6kx

    keeb_center:
      anchor:
        ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
        shift: [0, 0]

    #  Controller
    controller:
      anchor:
        ref: keeb_center
        shift: [0, -16]
      key:
        name: mcu
        width: mcu_x
        height: mcu_y

    #  Azoteq TPS65 Trackpad
    trackpad:
      anchor:
        ref: keeb_center
        shift: [0, -15]
      key:
        name: trackpad
        width: 65
        height: 49

outlines:
  _keys:
    - what: rectangle
      where: [[key, -enter, -space]]
      size: [kx/2, ky/2]

  pcb_outline:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [-0.75kx, 0.75ky]
        - ref: matrix_inner_top
          shift: [0.75kx, 0.75ky]
        - ref: mirror_matrix_inner_top
          shift: [0.75kx, 0.75ky]
        - ref: mirror_matrix_pinky_top
          shift: [-0.75kx, 0.75ky ]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.75kx, -0.75ky ]
        - ref: mirror_thumb_cluster_one_thumb_row
          shift: [ -0.75kx, -0.75ky ]
        - ref: mirror_thumb_cluster_three_thumb_row
          shift: [ 0.75kx, -0.75ky ]
        - ref: thumb_cluster_three_thumb_row
          shift: [0.75kx, -0.75ky]
        - ref: thumb_cluster_one_thumb_row
          shift: [-0.75kx, -0.75ky]
        - ref: matrix_pinky_bottom
          shift: [-0.75kx, -0.75ky]

  top:
    - name: pcb_outline
    - operation: subtract
      name: _keys

  bottom:
    - name: pcb_outline

pcbs:
  board:
    outlines:
      left:
        outline: pcb_outline
    footprints:
      choc:
        what: choc
        where:
          - /matrix_.*/
          - /thumb_cluster_.*/
        params:
          show_keycaps: true
          reverse: false
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: diode
        where:
          - /matrix_.*/
          - /thumb_cluster_.*/
        params:
          include_tht: false
          from: "{{colrow}}"
          to: "{{row_net}}"
          designator: "D"
        adjust:
          shift: [-1.4, -6]
          rotate: 180
      # Controller Area
      promicro:
        what: promicro
        params:  # Pin Assignments (Controller on top facing down)
          orientation: "up"
          # Left side of MCU
          P0: "R0" # Left Row
          P1: "R1" # Left Row
          # GND
          # GND
          P2: "SDA" # I2C
          P3: "SCL" # I2C
          P4: "R2" # Left Row
          P5: "R3" # Left Row
          P6: "R4" # Right Row
          P7: "R5" # Right Row
          P8: "R6" # Right Row
          P9: "R7" # Right Row

          # Right side of MCU
          # RAW
          # GND       # Ground
          # RST       # Reset pin
          # VCC       # External Power
          P21: "C0" # Column
          P20: "C1" # Column
          P19: "C2" # Column
          P18: "C3" # Column
          P15: "C4" # Column
          # P14:
          # P16:
          # P10:

        where:
          ref: mcu
          shift: [0, 0]
          rotate: -90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: keeb_center
          shift: [0, -36]
      trackpad:
        what: azoteq_trackpad
        params:

        where:
          ref: trackpad
      github:
        what: text_metal
        where:
          ref: matrix_inner_top
          shift: [25, 0]
        params:
          text: "github/com/TildeWill/magellan"
          h_size: 2
