units:
  kx: cx
  ky: cy
  px: kx
  py: ky
  kxo: 0.5 * kx
  kyo: 0.5 * ky

  # Kailh Choc v1
  plate_kx: kx
  plate_ky: ky

  # Font units
  font_x: 1
  font_y: 1
  font_xo: 0.5 font_x
  font_yo: 0.5 * font_y

  # MCU
  mcu_overhang_y: 2.54
  mcu_spacing_x: 2.72
  mcu_x: 17.78 + mcu_spacing_x
  mcu_y: 30.48 + mcu_overhang_y

points:
  key:
    padding: ky
    spread: kx
    width: kx
    height: ky
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [35, -100]
      key.tags: key
      columns:
        pinky:
          key.column_net: C0
        ring:
          key.column_net: C1
        middle:
          key.column_net: C2
        index:
          key.column_net: C3
        inner:
          key.column_net: C5

      rows:
        bottom:
          row_net: R4
        home:
          row_net: R3
        top:
          row_net: R2
      mirror: &mirror
        ref: matrix_inner_top
        distance: 6kx

    thumb_cluster:
      key:
        tags: key
      anchor:
        ref: matrix_inner_bottom
        shift: [0, -1ky]
      columns:
        one:
          key.column_net: C0
        two:
          key.column_net: C1
        three:
          key.column_net: C2
      rows:
        thumb_row:
          row_net: R7

      mirror: &thumb_mirror
        ref: matrix_inner_top
        distance: 6kx

    keeb_center:
      anchor:
        ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
        shift: [0, 0]

    #  Controller
    controller:
      anchor:
        ref: keeb_center
        shift: [0, 0]
      key:
        name: mcu
        width: mcu_x
        height: mcu_y

    #  Azoteq TPS65 Trackpad
    trackpad:
      anchor:
        ref: keeb_center
        shift: [0, -15]
      key:
        name: trackpad
        width: 65
        height: 39



outlines:
  _keys:
    - what: rectangle
      where: [[key, -enter, -space]]
      size: [plate_kx/2, plate_ky/2]

  _outline:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [-0.75kx, 0.5ky]
        - ref: matrix_inner_top
          shift: [0.75kx, 0.5ky]
        - ref: mirror_matrix_inner_top
          shift: [0.75kx, 0.5ky]
        - ref: mirror_matrix_pinky_top
          shift: [-0.75kx, 0.5ky ]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.75kx, -0.5ky ]
        - ref: mirror_thumb_cluster_one_thumb_row
          shift: [ -0.75kx, -0.5ky ]
        - ref: mirror_thumb_cluster_three_thumb_row
          shift: [ 0.75kx, -0.5ky ]
        - ref: thumb_cluster_three_thumb_row
          shift: [0.75kx, -0.5ky]
        - ref: thumb_cluster_one_thumb_row
          shift: [-0.75kx, -0.5ky]

        - ref: matrix_pinky_bottom
          shift: [-0.75kx, -0.5ky]

  _mcuears:
    - what: rectangle
      size: [mcu_x +10, 6ky]
      fillet: 2

  pcb_outline:
    - name: _outline
    - operation: add
      name: _mcuears
      where:
        ref: matrix_pinky_top
        shift: [0.75 * kx + mcu_x/2 -5, -2.5ky]

  top:
    - name: _outline
    - operation: subtract
      name: _keys


  bottom:
    - name: pcb_outline

pcbs:
  board:
    outlines:
      left:
        outline: pcb_outline
    footprints:
      choc:
        what: choc
        where:
          - /^matrix_.*/
          - /thumb_cluster_.*/
          - /^spaces_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: diode
        where:
          - /^matrix_.*/
          - /thumb_cluster_.*/
          - /^spaces_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          designator: "D"
        adjust:
          shift: [-1.4, -6]
          rotate: 180
      # Controller Area
      promicro:
        what: promicro
        params:
          # Pin Assignments (Controller on top facing down)
          # Right Side
          P0: "DPD" # Display Data
          P1: "DPC" # Display Clock
          # GND
          # GND
          P2: "DPE" # Display CS (nice!view only) FIXME? ZPM default?
          P3: "R1" # Row
          P4: "R2" # Row
          P5: "R3" # Row
          P6: "R4" # Row
          P7: "R5" # Row
          P8: "R6" # Row
          P9: "R7" # Row

          # Left Side
          RAW: "BAT_P" # Battery Pos
          # GND       # Ground / Battery Neg
          # RST       # Reset pin
          # VCC       # External Power
          P21: "C0" # Column
          P20: "C1" # Column
          P19: "C2" # Column
          P18: "C3" # Column
          P15: "C4" # Column
          P14: "C5" # Column
          P16: "C6" # Column
          P10: "F10" # Free

        where:
          ref: mcu
          shift: [0, 0]
          rotate: -90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: mcu
          shift: [mcu_x, -mcu_y/2 - 8]
