meta:
  engine: 4.0.4
  name: magellan
  version: 0.1
  author: TildeWill
  url: https://github.com/tildewill/magellan
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
points:
  zones:
    # The primary 6x4 key matrix, plus 3 modifiers.
    matrix:
      anchor:
        shift: [100, -100] # Fix placement on KiCAD sheet.
      # Choc spacing
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          key.column_net: P14
        ring:
          key.column_net: P16
        middle:
          key.column_net: P10
        index:
          key.column_net: P7
        inner:
          key.column_net: P8
      rows:
        bottom:
          row_net: P15
          mirror.row_net: P6
        home:
          row_net: P18
          mirror.row_net: P5
        top:
          row_net: P19
          mirror.row_net: P4

    # Thumb cluster for Layer and Space keys.
    thumbs:
      # Choc spacing
      key:
        padding: 1ky
        spread: 1kx
      # Place thumbs where the inner mod would go.
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1ky]
      columns:
        left:
          key:
            column_net: P10
        center:
          key:
            column_net: P7
        right:
          key:
            column_net: P8

      rows:
        # Thumbs only have one row.
        cluster:
  # Mirror keyboard halves with a moderate rotation.
  rotate: -15
  mirror: &mirror
    ref: matrix_inner_bottom
    distance: 7kx
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      fillet: 3
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_inner_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_index_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_left_cluster
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_right_cluster
          shift: [0.5px,-0.5py]
        - ref: thumbs_right_cluster
          shift: [0.5px,-0.5py]
        - ref: thumbs_left_cluster
          shift: [-0.5px,-0.5py]
        - ref: matrix_index_bottom
          shift: [-0.5px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
  combo:
    - name: board
    - operation: subtract
      name: keys
    #- operation: add
    #  name: trackpad
pcbs:
  tutorial:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0,-12]
          rotate: -90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref.aggregate.parts: [matrix_index_bottom, mirror_matrix_index_bottom]
          shift: [0, -5]
          rotate: -90
      info:
        what: text
        where:
          ref:
            - matrix_pinky_bottom
          shift: [0.75 kx, 0]
        params:
          text: "magellan v0.1\\nby TildeWill"
          justify: left
